{{- if .Values.schemaLoadJob.create -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}-schema-loader
  labels:
    component: {{ .Values.component }}
spec:
  serviceAccountName: {{ .Values.component }}
  template:
    spec:
      containers:
        - name: schema-loader
          image: 529080510656.dkr.ecr.us-east-1.amazonaws.com/schema-loader:2.0.3
          args: [ "{{ .Values.schemaLoadJob.type }}", "{{ .Values.component }}" ]
          env:
            - name: env
              value: {{ .Values.env }}
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 1f
{{- end }}

